name: scraper

on:
  schedule:
    - cron: '0 * * * *'

env:
  NODE_ENV: production

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.PAT}}
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.1
      - run: npm install -g @vue/cli@latest
      - run: npm ci
      - run: npm run build
      - run: npm run scraper
      - uses: stefanzweifel/git-auto-commit-action@v4.4.1
        with:
          file_pattern: README.md docs/*.md
          commit_message: 'docs: update categories'
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
